"""
Swahili Parity Orchestrator (English-Parity, English-First).
Auto-generated by engine_common.generator. Subclasses the shared
BaseEngineOrchestrator so this engine matches the English flagship pipeline:
English-pivot comprehension -> 4 Sub-AIs -> Six-Language Matrix -> Four-Stage
Matrix -> 64-byte AMSV synchronisation. Language behaviour comes from the
"Swahili_engine" LanguageProfile (Swahili, SVO, Latin).
"""

from __future__ import annotations
from typing import Optional

from amsv.python.amsv_embedded import AMSVEmbeddedView
from engine_common.base_orchestrator import BaseEngineOrchestrator, EngineComprehensiveOutput
from engine_common.language_profile import get_profile


class SwahiliParityOrchestrator(BaseEngineOrchestrator):
    """English-parity master orchestrator for the Swahili engine."""

    ENGINE_DIR = "Swahili_engine"

    def __init__(self, amsv_view: Optional[AMSVEmbeddedView] = None,
                 checkpoint_path: Optional[str] = None) -> None:
        super().__init__(profile=get_profile(self.ENGINE_DIR),
                         amsv_view=amsv_view, checkpoint_path=checkpoint_path)


def build_orchestrator(amsv_view: Optional[AMSVEmbeddedView] = None,
                       checkpoint_path: Optional[str] = None) -> SwahiliParityOrchestrator:
    return SwahiliParityOrchestrator(amsv_view=amsv_view, checkpoint_path=checkpoint_path)


if __name__ == "__main__":
    orch = build_orchestrator()
    out = orch.process("paka ni nzuri.")
    print(f"[Swahili] overall={out.overall_linguistic_score} "
          f"english_first='{out.english_pivot.english_projection}' "
          f"amsv_synced={out.amsv_synced}")
